export const BalanceProverABI = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  { inputs: [{ internalType: "address", name: "target", type: "address" }], name: "AddressEmptyCode", type: "error" },
  { inputs: [{ internalType: "address", name: "implementation", type: "address" }], name: "ERC1967InvalidImplementation", type: "error" },
  { inputs: [], name: "ERC1967NonPayable", type: "error" },
  { inputs: [], name: "FailedCall", type: "error" },
  { inputs: [], name: "InvalidInitialization", type: "error" },
  { inputs: [], name: "InvalidKMSSignatures", type: "error" },
  { inputs: [], name: "NotInitializing", type: "error" },
  { inputs: [{ internalType: "address", name: "owner", type: "address" }], name: "OwnableInvalidOwner", type: "error" },
  { inputs: [{ internalType: "address", name: "account", type: "address" }], name: "OwnableUnauthorizedAccount", type: "error" },
  { inputs: [{ internalType: "bytes32", name: "handle", type: "bytes32" }, { internalType: "address", name: "sender", type: "address" }], name: "SenderNotAllowedToUseHandle", type: "error" },
  { inputs: [], name: "UUPSUnauthorizedCallContext", type: "error" },
  { inputs: [{ internalType: "bytes32", name: "slot", type: "bytes32" }], name: "UUPSUnsupportedProxiableUUID", type: "error" },
  { inputs: [], name: "ZamaProtocolUnsupported", type: "error" },
  { anonymous: false, inputs: [{ indexed: false, internalType: "uint64", name: "version", type: "uint64" }], name: "Initialized", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "previousOwner", type: "address" }, { indexed: true, internalType: "address", name: "newOwner", type: "address" }], name: "OwnershipTransferred", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "prover", type: "address" }], name: "ProofCleared", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "prover", type: "address" }, { indexed: false, internalType: "bool", name: "result", type: "bool" }, { indexed: false, internalType: "uint256", name: "timestamp", type: "uint256" }], name: "ProofPublished", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "prover", type: "address" }, { indexed: false, internalType: "bytes32", name: "handle", type: "bytes32" }], name: "ProofRequested", type: "event" },
  { anonymous: false, inputs: [{ indexed: false, internalType: "bytes32[]", name: "handlesList", type: "bytes32[]" }, { indexed: false, internalType: "bytes", name: "abiEncodedCleartexts", type: "bytes" }], name: "PublicDecryptionVerified", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "implementation", type: "address" }], name: "Upgraded", type: "event" },
  { inputs: [], name: "UPGRADE_INTERFACE_VERSION", outputs: [{ internalType: "string", name: "", type: "string" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "clearProof", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "cusdc", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "user", type: "address" }], name: "getProof", outputs: [{ components: [{ internalType: "bool", name: "result", type: "bool" }, { internalType: "uint256", name: "timestamp", type: "uint256" }, { internalType: "bool", name: "exists", type: "bool" }], internalType: "struct BalanceProver.ProofResult", name: "", type: "tuple" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "cusdcAddress", type: "address" }, { internalType: "address", name: "owner_", type: "address" }], name: "initialize", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "owner", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "user", type: "address" }], name: "pendingHandle", outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "", type: "address" }], name: "proofResults", outputs: [{ internalType: "bool", name: "result", type: "bool" }, { internalType: "uint256", name: "timestamp", type: "uint256" }, { internalType: "bool", name: "exists", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "bytes32", name: "encryptedThreshold", type: "bytes32" }, { internalType: "bytes", name: "inputProof", type: "bytes" }], name: "proveAbove", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "proxiableUUID", outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "prover", type: "address" }, { internalType: "bytes", name: "cleartexts", type: "bytes" }, { internalType: "bytes", name: "decryptionProof", type: "bytes" }], name: "publishProof", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "renounceOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "newOwner", type: "address" }], name: "transferOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "newImplementation", type: "address" }, { internalType: "bytes", name: "data", type: "bytes" }], name: "upgradeToAndCall", outputs: [], stateMutability: "payable", type: "function" },
] as const;
