export const PayrollVaultABI = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  { inputs: [{ internalType: "address", name: "target", type: "address" }], name: "AddressEmptyCode", type: "error" },
  { inputs: [{ internalType: "address", name: "implementation", type: "address" }], name: "ERC1967InvalidImplementation", type: "error" },
  { inputs: [], name: "ERC1967NonPayable", type: "error" },
  { inputs: [], name: "FailedCall", type: "error" },
  { inputs: [], name: "InvalidInitialization", type: "error" },
  { inputs: [], name: "NotInitializing", type: "error" },
  { inputs: [{ internalType: "address", name: "owner", type: "address" }], name: "OwnableInvalidOwner", type: "error" },
  { inputs: [{ internalType: "address", name: "account", type: "address" }], name: "OwnableUnauthorizedAccount", type: "error" },
  { inputs: [{ internalType: "bytes32", name: "handle", type: "bytes32" }, { internalType: "address", name: "sender", type: "address" }], name: "SenderNotAllowedToUseHandle", type: "error" },
  { inputs: [], name: "UUPSUnauthorizedCallContext", type: "error" },
  { inputs: [{ internalType: "bytes32", name: "slot", type: "bytes32" }], name: "UUPSUnsupportedProxiableUUID", type: "error" },
  { inputs: [], name: "ZamaProtocolUnsupported", type: "error" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "employee", type: "address" }], name: "Claimed", type: "event" },
  { anonymous: false, inputs: [{ indexed: false, internalType: "uint64", name: "version", type: "uint64" }], name: "Initialized", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "previousOwner", type: "address" }, { indexed: true, internalType: "address", name: "newOwner", type: "address" }], name: "OwnershipTransferred", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "runId", type: "uint256" }], name: "RunCancelled", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "runId", type: "uint256" }, { indexed: true, internalType: "uint256", name: "templateId", type: "uint256" }], name: "RunCreated", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "runId", type: "uint256" }], name: "RunExecuted", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "runId", type: "uint256" }], name: "RunFunded", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "templateId", type: "uint256" }, { indexed: true, internalType: "address", name: "employer", type: "address" }], name: "TemplateCreated", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "implementation", type: "address" }], name: "Upgraded", type: "event" },
  { inputs: [], name: "UPGRADE_INTERFACE_VERSION", outputs: [{ internalType: "string", name: "", type: "string" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "runId", type: "uint256" }], name: "cancelRun", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "claim", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "templateId", type: "uint256" }, { internalType: "bytes32[]", name: "salaries", type: "bytes32[]" }, { internalType: "bytes[]", name: "proofs", type: "bytes[]" }], name: "createRun", outputs: [{ internalType: "uint256", name: "runId", type: "uint256" }], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address[]", name: "employees", type: "address[]" }], name: "createTemplate", outputs: [{ internalType: "uint256", name: "templateId", type: "uint256" }], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "cusdc", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "runId", type: "uint256" }], name: "executeRun", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "runId", type: "uint256" }], name: "fundRun", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "templateId", type: "uint256" }], name: "getEmployees", outputs: [{ internalType: "address[]", name: "", type: "address[]" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "runId", type: "uint256" }], name: "getRunStatus", outputs: [{ internalType: "uint256", name: "templateId", type: "uint256" }, { internalType: "bool", name: "funded", type: "bool" }, { internalType: "bool", name: "executed", type: "bool" }, { internalType: "bool", name: "cancelled", type: "bool" }, { internalType: "uint256", name: "executedAt", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "templateId", type: "uint256" }], name: "getTemplate", outputs: [{ internalType: "address", name: "employer", type: "address" }, { internalType: "bool", name: "active", type: "bool" }, { internalType: "uint256", name: "createdAt", type: "uint256" }, { internalType: "uint256", name: "employeeCount", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "cusdcAddress", type: "address" }, { internalType: "address", name: "owner_", type: "address" }], name: "initialize", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "owner", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "employee", type: "address" }], name: "pendingClaim", outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "proxiableUUID", outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "renounceOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "runCount", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "runId", type: "uint256" }], name: "runTotal", outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "runId", type: "uint256" }, { internalType: "address", name: "employee", type: "address" }], name: "salaryOf", outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "templateCount", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "newOwner", type: "address" }], name: "transferOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "newImplementation", type: "address" }, { internalType: "bytes", name: "data", type: "bytes" }], name: "upgradeToAndCall", outputs: [], stateMutability: "payable", type: "function" },
] as const;
